package librarymanagementsystem.GUI;

import java.awt.*;
import java.awt.event.KeyEvent;
import librarymanagementsystem.BUS.*;

public class LoginGUI extends javax.swing.JFrame{
    private javax.swing.JPanel exit_btn;
    private javax.swing.JLabel jLabel_password;
    private javax.swing.JLabel jLabel_username;
    private javax.swing.JLabel login_form;
    private javax.swing.JPanel pLogin;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JTextField username_field;
    
    public LoginGUI() {
        initComponents();
        setSize(530, 340);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
        jLabel_username.setBackground(new Color(0, 0, 0, 0));
        jLabel_password.setBackground(new Color(0, 0, 0, 0));
        username_field.setBackground(new Color(0, 0, 0, 0));
        password_field.setBackground(new Color(0, 0, 0, 0));
        username_field.setVisible(false);
        password_field.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        pLogin = new javax.swing.JPanel();
        jLabel_username = new javax.swing.JLabel();
        jLabel_password = new javax.swing.JLabel();
        username_field = new javax.swing.JTextField();
        password_field = new javax.swing.JPasswordField();
        exit_btn = new javax.swing.JPanel();
        login_form = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        pLogin.setOpaque(false);
        pLogin.setLayout(null);

        jLabel_username.setBackground(new java.awt.Color(91, 231, 196));
        jLabel_username.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel_username.setForeground(new java.awt.Color(245, 247, 250));
        jLabel_username.setText("Username");
        jLabel_username.setMaximumSize(new java.awt.Dimension(83, 21));
        jLabel_username.setMinimumSize(new java.awt.Dimension(83, 21));
        jLabel_username.setPreferredSize(new java.awt.Dimension(83, 21));
        jLabel_username.setBounds(138, 197, 83, 21);
        
        jLabel_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_usernameMouseClicked(evt);
            }
        });
        pLogin.add(jLabel_username/*, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 197, -1, -1)*/);

        jLabel_password.setBackground(new java.awt.Color(91, 231, 196));
        jLabel_password.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel_password.setForeground(new java.awt.Color(245, 247, 250));
        jLabel_password.setText("Password");
        jLabel_password.setMaximumSize(new java.awt.Dimension(83, 21));
        jLabel_password.setMinimumSize(new java.awt.Dimension(83, 21));
        jLabel_password.setPreferredSize(new java.awt.Dimension(83, 21));
        jLabel_password.setBounds(138, 250, 83, 21);
        jLabel_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_passwordMouseClicked(evt);
            }
        });
        pLogin.add(jLabel_password/*, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 250, -1, -1)*/);

        username_field.setBackground(new java.awt.Color(91, 231, 196));
        username_field.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        username_field.setForeground(new java.awt.Color(245, 247, 250));
        username_field.setBorder(null);
        username_field.setOpaque(false);
        username_field.setPreferredSize(new java.awt.Dimension(83, 21));
        username_field.setBounds(138, 197, 280, 21);
        /*username_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                username_fieldFocusGained(evt);
            }
        });*/
        username_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_fieldKeyPressed(evt);
            }
        });
        pLogin.add(username_field/*, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 197, 280, -1)*/);

        password_field.setBackground(new java.awt.Color(91, 231, 196));
        password_field.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        password_field.setForeground(new java.awt.Color(245, 247, 250));
        password_field.setBorder(null);
        password_field.setOpaque(false);
        password_field.setPreferredSize(new java.awt.Dimension(80, 21));
        password_field.setBounds(138, 250, 280, 21);
        /*password_field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                password_fieldFocusGained(evt);
            }
        });*/
        password_field.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_fieldKeyPressed(evt);
            }
        });
        pLogin.add(password_field/*, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 250, 280, -1)*/);

        exit_btn.setOpaque(false);
        exit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_btnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout exit_btnLayout = new javax.swing.GroupLayout(exit_btn);
        exit_btn.setLayout(exit_btnLayout);
        exit_btn.setBounds(470, 20, 30, 30);
        exit_btnLayout.setHorizontalGroup(
            exit_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        exit_btnLayout.setVerticalGroup(
            exit_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        pLogin.add(exit_btn/*, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 30, 30)*/);
        pLogin.setBounds(0, 0, 530, 340);
        login_form.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/login.png"))); // NOI18N
        login_form.setBounds(10, 10, 500, 312);
        /*login_form.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_formFocusGained(evt);
            }
        });*/
        pLogin.add(login_form/*, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1)*/);
        
        getContentPane().add(pLogin/*, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 340)*/);

        pack();
    }// </editor-fold>                        

    /*private void login_formFocusGained(java.awt.event.FocusEvent evt) {                                       
        
    }*/                                     

    private void exit_btnMouseClicked(java.awt.event.MouseEvent evt) {                                      
        System.exit(0);
    }                                     

    /*private void password_fieldFocusGained(java.awt.event.FocusEvent evt) {                                           
        //jLabel_password.setVisible(false);
        //jPasswordField1.setVisible(true);
    } */                                         

    /*private void username_fieldFocusGained(java.awt.event.FocusEvent evt) {                                           
        //jLabel_username.setVisible(false);
        //jTextField1.setVisible(true);
    } */                                         

    private void jLabel_usernameMouseClicked(java.awt.event.MouseEvent evt) {                                             
        jLabel_username.setVisible(false);
        username_field.setVisible(true);
        username_field.requestFocus();
    }                                            

    private void jLabel_passwordMouseClicked(java.awt.event.MouseEvent evt) {                                             
        jLabel_password.setVisible(false);
        password_field.setVisible(true);
        password_field.requestFocus();
    }                              
    
    Boolean kiemTraDangNhap(){
        QLAdminBUS tkadmin = new QLAdminBUS();
        if (tkadmin.kiemTraTaiKhoan(username_field.getText(), password_field.getText())){
            return true;
        }
        
        QLNhanVienBUS tknhanvien = new QLNhanVienBUS();
        if (tknhanvien.kiemTraTaiKhoan(username_field.getText(), password_field.getText())){
            return true;
        }
        
        return false;
    }

    private void formKeyPressed(java.awt.event.KeyEvent evt) {                                
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.out.println("Đăng Nhập" + " " + username_field.getText() + " " + password_field.getText());
            if (kiemTraDangNhap()){
                System.out.println("Đăng Nhập Thành Công");
            }
            else{
                System.out.println("Đăng Nhập Thất Bại");
            }
        }
    }                               

    private void username_fieldKeyPressed(java.awt.event.KeyEvent evt) {                                          
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.out.println("Đăng Nhập" + " " + username_field.getText() + " " + password_field.getText());
            if (kiemTraDangNhap()){
                System.out.println("Đăng Nhập Thành Công");
            }
            else{
                System.out.println("Đăng Nhập Thất Bại");
            }
        }
    }                                         

    private void password_fieldKeyPressed(java.awt.event.KeyEvent evt) {                                          
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            System.out.println("Đăng Nhập" + " " + username_field.getText() + " " + password_field.getText());
            if (kiemTraDangNhap()){
                System.out.println("Đăng Nhập Thành Công");
            }
            else{
                System.out.println("Đăng Nhập Thất Bại");
            }
        }
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginGUI().setVisible(true);
            }
        });
    }
    
}
