package librarymanagementsystem.GUI;

import librarymanagementsystem.GUI.Table.*;
import java.awt.*;
import java.awt.event.KeyEvent;
import javax.swing.*;

public class MainGUI extends javax.swing.JFrame{
    int x_Mouse, y_Mouse; // For Moving Window
    static String currentUser = "";
    ExitGUI exitForm;
    
    public MainGUI() {
        initComponents();
        setSize(1020, 680);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }
    
    public MainGUI(String currentUser) {
        this.currentUser = currentUser;
        System.out.println("Welcome " + currentUser);
        initComponents();
        setSize(1020, 680);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        moreInfoUser_Label = new javax.swing.JLabel();
        username_Label = new javax.swing.JLabel();
        iconUser_Label = new javax.swing.JLabel();
        movingWindow = new javax.swing.JLabel();
        homeModule = new javax.swing.JLabel();
        sachModule = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        mainGUI_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/exit_20_20.png"))); // NOI18N
        exitButton.setBounds(970, 15, 20, 20); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        jPanel1.add(exitButton);
        
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setText("NHÀ CUNG CẤP");
        jLabel2.setBounds(130, 10, 100, 30);
        jPanel1.add(jLabel2);
        
        moreInfoUser_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/moreinfo_20_20.png"))); // NOI18N
        moreInfoUser_Label.setBounds(930, 20, 20, 20); // NOI18N
        moreInfoUser_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moreInfoUser_LabelMouseClicked(evt);
            }
        });
        jPanel1.add(moreInfoUser_Label);

        username_Label.setFont(new java.awt.Font("Consolas", 3, 18)); // NOI18N
        username_Label.setForeground(new java.awt.Color(102, 102, 102));
        username_Label.setText("Lưu Thành Đạt");
        username_Label.setBounds(790, 17, 130, 22);
        jPanel1.add(username_Label);

        iconUser_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/iconuser_32_32.png"))); // NOI18N
        iconUser_Label.setBounds(750, 10, 32, 32); // NOI18N
        jPanel1.add(iconUser_Label);

        movingWindow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movingWindowMouseDragged(evt);
            }
        });
        movingWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movingWindowMousePressed(evt);
            }
        });
        movingWindow.setBounds(0, 0, 1020, 50);
        jPanel1.add(movingWindow);

        homeModule.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/homemodule_32_32.png"))); // NOI18N
        homeModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeModuleMouseClicked(evt);
            }
        });
        homeModule.setBounds(15, 100, 32, 32);
        jPanel1.add(homeModule);

        sachModule.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/sachmodule_32_32.png"))); // NOI18N
        sachModule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sachModuleMouseClicked(evt);
            }
        });
        sachModule.setBounds(15, 170, 32, 32);
        jPanel1.add(sachModule);
        
        /**/
        jButton1.setBackground(new java.awt.Color(104, 104, 104));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.setBorderPainted(false);
        jButton1.setBounds(300, 80, 80, 40);
        jPanel1.add(jButton1);

        jButton2.setBackground(new java.awt.Color(104, 104, 104));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Sửa");
        jButton2.setBorderPainted(false);
        jButton2.setBounds(580, 80, 80, 40);
        jPanel1.add(jButton2);

        jButton3.setBackground(new java.awt.Color(104, 104, 104));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Xóa");
        jButton3.setBorderPainted(false);
        jButton3.setBounds(440, 80, 80, 40);
        jPanel1.add(jButton3);

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Tìm Kiếm");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setOpaque(true);
        jLabel1.setBounds(580, 150, 80, 40);
        jPanel1.add(jLabel1);

        jTextField1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(204, 204, 204));
        jTextField1.setText("");
        jTextField1.setBounds(280, 150, 280, 40);
        jPanel1.add(jTextField1); 
        
            
        //PaginationExampleMain table = new PaginationExampleMain();
        //JPanel table_panel = table.get_table();
        //table_panel.setBounds(100, 200, 800, 420);
        //table_panel.setBackground(new java.awt.Color(255, 255, 255));
        //jPanel1.add(table_panel);
        
        /**/

        mainGUI_Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("../images/mainGUI.png"))); // NOI18N
        mainGUI_Label.setBounds(0, 0, 1020, 680); // NOI18N
        jPanel1.add(mainGUI_Label);
        jPanel1.setBounds(0, 0, 1020, 680);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>                        

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {                                        
        //System.exit(0);
        if (exitForm == null || !exitForm.isDisplayable()){ // Hiển thị 1 windows tại 1 thời điểm 
            exitForm = new ExitGUI();
            exitForm.setVisible(true);
        }
    }                                       

    private void movingWindowMouseDragged(java.awt.event.MouseEvent evt) {                                          
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        setLocation(x - x_Mouse, y - y_Mouse);
    }                                         

    private void movingWindowMousePressed(java.awt.event.MouseEvent evt) {                                          
        x_Mouse = evt.getX();
        y_Mouse = evt.getY();
    }                                         

    private void moreInfoUser_LabelMouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void homeModuleMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void sachModuleMouseClicked(java.awt.event.MouseEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel homeModule;
    private javax.swing.JLabel iconUser_Label;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel mainGUI_Label;
    private javax.swing.JLabel moreInfoUser_Label;
    private javax.swing.JLabel movingWindow;
    private javax.swing.JLabel sachModule;
    private javax.swing.JLabel username_Label;
    // End of variables declaration      
}
