/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem.GUI.ThemSuaGUI;

import java.awt.Color;
import java.awt.FileDialog;
//import librarymanagementsystem.DTO.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import librarymanagementsystem.BUS.QLAdminBUS;
import librarymanagementsystem.GUI.*;
import librarymanagementsystem.Toolkit.DataProcessing;
import librarymanagementsystem.BUS.QLLoaiSachBUS;
import librarymanagementsystem.DTO.QLLoaiSachDTO;

/**
 *
 * @author NTH
 */
public class SuaLoaiSachForm extends javax.swing.JFrame {

    int x_Mouse, y_Mouse; // For Moving Window
    FileDialog fx = new FileDialog(new JFrame(), "Thêm hình sách", FileDialog.LOAD);
    static String error_mess;
    DataProcessing dp = new DataProcessing();
    String url = ""; // đường dẫn hình sách
    static QLLoaiSachBUS loaisachBUS = new QLLoaiSachBUS();
    String ms;
    
    public SuaLoaiSachForm(String maSach) {
        QLLoaiSachDTO sach = new QLLoaiSachBUS().getLoaiSach(maSach);
        ms = maSach;
        url = sach.getHinh();
        initComponents(sach.getTenSach(), sach.getTenTacGia(), sach.getTenNXB(), sach.getTheLoai(), sach.getNgonNgu(), Integer.toString(sach.getNamXB()), sach.getTomTatNoiDung(), Integer.toString(sach.getSoTrang()), Integer.toString(sach.getGiaTien()), sach.getHinh());
        setSize(830, 523);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(String tenSach, String tenTacGia, String tenNXB, String tenTheLoai, String ngonNgu, String namXB, String tomTatNoiDung, String giaTien, String soTrang, String hinhSach) {

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        addHinh = new javax.swing.JLabel();
        movingWindow = new javax.swing.JLabel();
        tenSach_textField = new javax.swing.JTextField();
        tenTacGia_textField = new javax.swing.JTextField();
        tenNXB_textField = new javax.swing.JTextField();
        tenTheLoai_textField = new javax.swing.JTextField();
        ngonNgu_textField = new javax.swing.JTextField();
        namXuatBan_textField = new javax.swing.JTextField();
        giaTien_textField = new javax.swing.JTextField();
        soTrang_textField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tomTatNoiDung_textArea = new javax.swing.JTextArea();
        hinh_label = new javax.swing.JLabel();
        loaiSachForm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools - 2020-05-28T235936.194.png"))); // NOI18N
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.setBounds(20, 10, 35, 35);
        jPanel1.add(addButton);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools (43).png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.setBounds(782, 20, 20, 20);
        jPanel1.add(exitButton);

        addHinh.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools - 2020-05-29T000010.861.png"))); // NOI18N
        addHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addHinhMouseClicked(evt);
            }
        });
        addHinh.setBounds(650, 390, 40, 40);
        jPanel1.add(addHinh);

        movingWindow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movingWindowMouseDragged(evt);
            }
        });
        movingWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movingWindowMousePressed(evt);
            }
        });
        movingWindow.setBounds(0, 0, 830, 60);
        jPanel1.add(movingWindow);

        tenSach_textField.setBackground(new java.awt.Color(245, 247, 250));
        tenSach_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenSach_textField.setText(tenSach);
        tenSach_textField.setBorder(null);
        tenSach_textField.setOpaque(false);
        tenSach_textField.setBounds(60, 130, 210, 30);
        jPanel1.add(tenSach_textField);

        tenTacGia_textField.setBackground(new java.awt.Color(245, 247, 250));
        tenTacGia_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenTacGia_textField.setText(tenTacGia);
        tenTacGia_textField.setBorder(null);
        tenTacGia_textField.setOpaque(false);
        tenTacGia_textField.setBounds(60, 230, 210, 30);
        jPanel1.add(tenTacGia_textField);

        tenNXB_textField.setBackground(new java.awt.Color(245, 247, 250));
        tenNXB_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenNXB_textField.setText(tenNXB);
        tenNXB_textField.setBorder(null);
        tenNXB_textField.setOpaque(false);
        tenNXB_textField.setBounds(60, 330, 210, 30);
        jPanel1.add(tenNXB_textField);

        tenTheLoai_textField.setBackground(new java.awt.Color(245, 247, 250));
        tenTheLoai_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tenTheLoai_textField.setText(tenTheLoai);
        tenTheLoai_textField.setBorder(null);
        tenTheLoai_textField.setOpaque(false);
        tenTheLoai_textField.setBounds(60, 430, 210, 30);
        jPanel1.add(tenTheLoai_textField);

        ngonNgu_textField.setBackground(new java.awt.Color(245, 247, 250));
        ngonNgu_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ngonNgu_textField.setText(ngonNgu);
        ngonNgu_textField.setBorder(null);
        ngonNgu_textField.setOpaque(false);
        ngonNgu_textField.setBounds(360, 130, 210, 30);
        jPanel1.add(ngonNgu_textField);

        namXuatBan_textField.setBackground(new java.awt.Color(245, 247, 250));
        namXuatBan_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namXuatBan_textField.setText(namXB);
        namXuatBan_textField.setBorder(null);
        namXuatBan_textField.setOpaque(false);
        namXuatBan_textField.setBounds(650, 130, 110, 30);
        jPanel1.add(namXuatBan_textField);

        giaTien_textField.setBackground(new java.awt.Color(245, 247, 250));
        giaTien_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        giaTien_textField.setText(giaTien);
        giaTien_textField.setBorder(null);
        giaTien_textField.setOpaque(false);
        giaTien_textField.setBounds(360, 430, 110, 30);
        jPanel1.add(giaTien_textField);

        soTrang_textField.setBackground(new java.awt.Color(245, 247, 250));
        soTrang_textField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        soTrang_textField.setText(soTrang);
        soTrang_textField.setBorder(null);
        soTrang_textField.setOpaque(false);
        soTrang_textField.setBounds(510, 430, 110, 30);
        jPanel1.add(soTrang_textField);

        tomTatNoiDung_textArea.setColumns(20);
        tomTatNoiDung_textArea.setRows(5);
        tomTatNoiDung_textArea.setBorder(null);
        tomTatNoiDung_textArea.setText(tomTatNoiDung);
        tomTatNoiDung_textArea.setWrapStyleWord(true);
        tomTatNoiDung_textArea.setLineWrap(true);
        jScrollPane1.setViewportView(tomTatNoiDung_textArea);
        jScrollPane1.setBounds(352, 234, 405, 126);

        jPanel1.add(jScrollPane1);

        hinh_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hinh_label.setBounds(650, 434, 150, 20);
        hinh_label.setText(hinhSach);
        jPanel1.add(hinh_label);

        loaiSachForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools - 2020-06-10T112205.154.png"))); // NOI18N
        loaiSachForm.setBounds(0, 0, 830, 523);
        jPanel1.add(loaiSachForm);
        jPanel1.setBounds(0, 0, 830, 523);
        
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean check_input(String tenSach, String tenTacGia, String tenNXB, String tenTheLoai, String ngonNgu, String namXuatBan, String giaTien, String soTrang, String tomTatNoiDung, String hinhSach){
        if (tenSach.equals("")){
            error_mess = "Tên Sách trống!!!";
            return false;
        }
        else if (tenTacGia.equals("")){
            error_mess = "Tên Tác Giả trống!!!";
            return false;
        }
        else if (tenNXB.equals("")){
            error_mess = "Tên NXB trống!!!";
            return false;
        }
        else if (tenTheLoai.equals("")){
            error_mess = "Tên Thể Loại trống!!!";
            return false;
        }
        else if (ngonNgu.equals("")){
            error_mess = "Ngôn Ngữ trống!!!";
            return false;
        }
        else if (namXuatBan.equals("")){
            error_mess = "Năm XB trống!!!";
            return false;
        }
        else if (giaTien.equals("")){
            error_mess = "Giá Tiền trống!!!";
            return false;
        }
        else if (soTrang.equals("")){
            error_mess = "Số Trang trống!!!";
            return false;
        }
        else if (tomTatNoiDung.equals("")){
            error_mess = "Tóm Tắt Nội Dung trống!!!";
            return false;
        }
        else if (hinhSach.equals("")){
            error_mess = "Hình Sách trống!!!";
            return false;
        }
        
        else if (!dp.check_nam(namXuatBan)){
            error_mess = "Năm XB nhập sai!!!";
            return false;
        }
        else if (!dp.check_number(giaTien) && giaTien.length() > 15){
            error_mess = "Giá Tiền nhập sai!!!";
            return false;
        }
        else if (!dp.check_number(soTrang) && soTrang.length() > 15){
            error_mess = "Số Trang nhập sai!!!";
            return false;
        }
        
        return true;
    }
    
    private void movingWindowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingWindowMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        setLocation(x - x_Mouse, y - y_Mouse);
    }//GEN-LAST:event_movingWindowMouseDragged

    
    private void movingWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingWindowMousePressed
        x_Mouse = evt.getX();
        y_Mouse = evt.getY();
    }//GEN-LAST:event_movingWindowMousePressed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        //QLLoaiSachDTO loaiSach = new QLLoaiSachDTO();
        String tenSach = tenSach_textField.getText();
        String tenTacGia = tenTacGia_textField.getText();
        String tenNXB = tenNXB_textField.getText();
        String tenTheLoai = tenTheLoai_textField.getText();
        String ngonNgu = ngonNgu_textField.getText();
        String namXuatBan = namXuatBan_textField.getText();
        String giaTien = giaTien_textField.getText();
        String soTrang = soTrang_textField.getText();
        String tomTatNoiDung = tomTatNoiDung_textArea.getText();
        String maSach = ms;
        
        if (check_input(tenSach, tenTacGia, tenNXB, tenTheLoai, ngonNgu, namXuatBan, giaTien, soTrang, tomTatNoiDung, url)){
            int option = JOptionPane.showConfirmDialog(
                null, 
                "Bạn có muốn sửa " + tenSach + " ?", 
                "Xóa Loại Sách", 
                JOptionPane.YES_NO_OPTION);
            if(option == JOptionPane.YES_OPTION){
                System.out.println("Nhập Thành Công");
                if (loaisachBUS.mod(maSach, tenSach, tenTacGia, tenNXB, tenTheLoai, ngonNgu, tomTatNoiDung, Integer.parseInt(namXuatBan), Integer.parseInt(giaTien), Integer.parseInt(soTrang), url) ){
                    new AlertGUI(3, "Success", "Sửa Loại Sách Thành Công!!!", "Quay Lại").setVisible(true);
                    this.dispose();
                }
            }
        }
        else{
            System.err.println(error_mess);
            System.out.println("Sửa Thất Bại");
            new AlertGUI(2, "Error", error_mess, "Quay Lại").setVisible(true);
            // Alert Form
        }
        
        System.out.println(maSach);
        System.out.println(tenSach);
        System.out.println(tenTacGia);
        System.out.println(tenNXB);
        System.out.println(tenTheLoai);
        System.out.println(ngonNgu);
        System.out.println(namXuatBan);
        System.out.println(giaTien);
        System.out.println(soTrang);
        System.out.println(tomTatNoiDung);
        System.out.println(url);
        
    }//GEN-LAST:event_addButtonMouseClicked

    private void addHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addHinhMouseClicked
        fx.setFile("*.png");
        fx.setVisible(true);
        url = fx.getDirectory() + fx.getFile();
        System.out.println(url);
        hinh_label.setText(fx.getFile());
    }//GEN-LAST:event_addHinhMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaLoaiSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaLoaiSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaLoaiSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaLoaiSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SuaLoaiSachForm("S000024").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addButton;
    private javax.swing.JLabel addHinh;
    private javax.swing.JLabel exitButton;
    private javax.swing.JTextField giaTien_textField;
    private javax.swing.JLabel hinh_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel loaiSachForm;
    private javax.swing.JLabel movingWindow;
    private javax.swing.JTextField namXuatBan_textField;
    private javax.swing.JTextField ngonNgu_textField;
    private javax.swing.JTextField soTrang_textField;
    private javax.swing.JTextField tenNXB_textField;
    private javax.swing.JTextField tenSach_textField;
    private javax.swing.JTextField tenTacGia_textField;
    private javax.swing.JTextField tenTheLoai_textField;
    private javax.swing.JTextArea tomTatNoiDung_textArea;
    // End of variables declaration//GEN-END:variables
}
