
package librarymanagementsystem.GUI.ThemSuaGUI;


import java.awt.Color;
import static java.awt.Component.CENTER_ALIGNMENT;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import librarymanagementsystem.GUI.*;
import librarymanagementsystem.Toolkit.DataProcessing;
import librarymanagementsystem.BUS.QLPhieuXuatBUS;
import librarymanagementsystem.DTO.QLPhieuXuatDTO;

public class ThemPhieuXuatForm extends javax.swing.JFrame{
    int x_Mouse, y_Mouse; // For Moving Window
    static String error_mess;
    DataProcessing dp = new DataProcessing();
    static QLPhieuXuatBUS pxBUS = new QLPhieuXuatBUS();
    
    
    
    public ThemPhieuXuatForm() {
        initComponents();
        setSize(830, 592);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        long millis=System.currentTimeMillis();  
        Date date=new java.sql.Date(millis); 

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        movingWindow = new javax.swing.JLabel();
        maNV_Label = new javax.swing.JTextField();
        ngayXuat_Label = new javax.swing.JLabel();
        nhanVienForm = new javax.swing.JLabel();
        taoRow_Label = new JLabel();
        tblCTPN = new JTable();
        save_Label=new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        model=new DefaultTableModel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools - 2020-05-28T235936.194.png"))); // NOI18N
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.setBounds(10, 7, 35, 35);
        jPanel1.add(addButton);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools (43).png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.setBounds(790, 16, 20, 20);
        jPanel1.add(exitButton);

        movingWindow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movingWindowMouseDragged(evt);
            }
        });
        movingWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movingWindowMousePressed(evt);
            }
        });
        movingWindow.setBounds(0, 0, 830, 60);
        jPanel1.add(movingWindow);
        
        
        maNV_Label.setBackground(new java.awt.Color(245, 247, 250));
        maNV_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maNV_Label.setText("dfgdfgdfg");
        maNV_Label.setBorder(null);
        maNV_Label.setOpaque(false);
        maNV_Label.setBounds(117, 105, 190, 30);
        jPanel1.add(maNV_Label);
        
        ngayXuat_Label.setBackground(new java.awt.Color(245, 247, 250));
        ngayXuat_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ngayXuat_Label.setText(date.toString());
        ngayXuat_Label.setBorder(null);
        ngayXuat_Label.setOpaque(false);
        ngayXuat_Label.setBounds(460, 105, 160, 30);
        jPanel1.add(ngayXuat_Label);
        
        save_Label=new JLabel("Save Table");
        save_Label.setBackground(new java.awt.Color(82, 210, 202));
        save_Label.setFont(new java.awt.Font("Tahoma", 0, 14));
        save_Label.setOpaque(true);
        save_Label.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        save_Label.setBounds(170, 150, 70, 40);
        jPanel1.add(save_Label);
        save_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                for(int i=0;i<tblCTPN.getRowCount();i++){
                    String maPhieuNhap = (String) tblCTPN.getModel().getValueAt(i, 0);
                    String maSach = (String) tblCTPN.getModel().getValueAt(i, 1);
                    System.out.println(maPhieuNhap);
                    System.out.println(maSach);
                    if(check_inputTable(maPhieuNhap, maSach)==true){
                        System.out.println("Lưu Thành Công");
                        new AlertGUI(3, "Success", "Lưu Thành Công!!!", "Quay Lại").setVisible(true);
                    }else{
                        System.err.println(error_mess);
                        System.out.println("Lưu Thất Bại");
                        new AlertGUI(2, "Error", error_mess, "Quay Lại").setVisible(true);
                    }
                }
            }
        });
        
        taoRow_Label=new JLabel("New Row");
        taoRow_Label.setBackground(new java.awt.Color(82, 210, 202));
        taoRow_Label.setFont(new java.awt.Font("Tahoma", 0, 14));
        taoRow_Label.setOpaque(true);
        taoRow_Label.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        taoRow_Label.setBounds(81, 150, 70, 40);
        jPanel1.add(taoRow_Label);
        taoRow_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vector header=new Vector();
                header.add("");
                header.add("");
                header.add("");
                jScrollPane1.getColumnHeader().setVisible(false);
                if(model.getRowCount()==0){
                    model=new DefaultTableModel(header, 0);
                }
                Vector row=new Vector();
                row.add(dp.next_maPhieuXuat(pxBUS.getPKey()));
                row.add("S");
                row.add("0");
                model.addRow(row);
                tblCTPN.setModel(model);
            }
        });
        String [] columnName={"MÃ PHIẾU XUÁT", "MÃ SÁCH", "SỐ LƯỢNG"};
        int x=80,y=208;
        headerFields=new JLabel[columnName.length];
        for(int i=0;i<columnName.length;i++){
            headerFields[i] = new JLabel(columnName[i]);
            headerFields[i].setBorder(BorderFactory.createLineBorder(Color.white));
            headerFields[i].setBounds(x, y, 223, 45);
            headerFields[i].setBackground(new java.awt.Color(82, 210, 202));
            headerFields[i].setFont(new java.awt.Font("Tahoma", 0, 14));
            headerFields[i].setOpaque(true);
            headerFields[i].setHorizontalAlignment((int) CENTER_ALIGNMENT);
            x=x+223;
            jPanel1.add(headerFields[i]);
        }
        jScrollPane1.setViewportView(tblCTPN);
        jScrollPane1.setBounds(80, 250, 670, 300);
        tblCTPN.setRowHeight(40);
        
        jPanel1.add(jScrollPane1);

        nhanVienForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtoolsthempx.png"))); // NOI18N
        nhanVienForm.setBounds(0, 0, 830, 592);
        jPanel1.add(nhanVienForm);
        jPanel1.setBounds(0, 0, 830, 592);
        
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean check_inputTable(String maPX, String maSach){
        if (maPX.equals("")){
            error_mess = "Mã Phiếu Xuất trống!!!";
            return false;
        }
        if (maSach.equals("")){
            error_mess = "Mã Sách trống!!!";
            return false;
        }
        if (dp.check_maPhieuXuat(maPX)!=true){
            error_mess = "Mã Phiếu Xuất nhập sai!!!";
            return false;
        }
        if (dp.check_maSach(maSach)!=true){
            error_mess = "Mã Sách nhập sai!!!";
            return false;
        }
        return true;
    }
    
    private boolean check_input(String maNV, String ngayXuat){
        if (maNV.equals("")){
            error_mess = "Mã Nhân Viên trống!!!";
            return false;
        }
        
        if (ngayXuat.equals("")){
            error_mess = "Ngày Xuất trống!!!";
            return false;
        }
        if (dp.check_maQuanLy(maNV)!=true){
            error_mess = "Mã Nhân Viên nhập sai!!!";
            return false;
        }
        if (dp.check_ngaythangnam(ngayXuat)!=true){
            error_mess = "Ngày Xuất nhập sai!!!";
            return false;
        }
        
        return true;
    }
    
    private void movingWindowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingWindowMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        setLocation(x - x_Mouse, y - y_Mouse);
    }//GEN-LAST:event_movingWindowMouseDragged

    
    private void movingWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingWindowMousePressed
        x_Mouse = evt.getX();
        y_Mouse = evt.getY();
    }//GEN-LAST:event_movingWindowMousePressed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private ArrayList<String> getMaSach(){
        ArrayList<String> arrMS =new ArrayList<>();
        for(int i=0;i<tblCTPN.getRowCount();i++){
            String maSach = (String) tblCTPN.getModel().getValueAt(i, 1);
            arrMS.add(maSach);
        }
        return arrMS;
    }
    private ArrayList<Integer> getSoLuong(){
        ArrayList<Integer> arrSL =new ArrayList<>();
        for(int i=0;i<tblCTPN.getRowCount();i++){
            int soLuong = Integer.parseInt((String) tblCTPN.getModel().getValueAt(i, 2));
            arrSL.add(soLuong);
        }
        return arrSL;
    }
        
    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {
        String maNV = maNV_Label.getText();
        String ngayXuat = ngayXuat_Label.getText();
        String maPhieuXuat = dp.next_maPhieuXuat(pxBUS.getPKey());
        ArrayList<String> maSach = getMaSach();
        ArrayList<Integer> soLuong =getSoLuong();
        System.out.println(maSach);
        System.out.println(soLuong);
        if (check_input(maNV, ngayXuat)){
            System.out.println("Nhập Thành Công");
            if (pxBUS.add(maPhieuXuat, ngayXuat, maSach, soLuong, maNV, 0)){
                new AlertGUI(3, "Success", "Nhập Phiếu Xuất Thành Công!!!", "Quay Lại").setVisible(true);
                this.dispose();
            }
        }
        else{
            System.err.println(error_mess);
            System.out.println("Nhập Thất Bại");
            new AlertGUI(2, "Error", error_mess, "Quay Lại").setVisible(true);
            // Alert Form
        }
        
        System.out.println(maNV);
        System.out.println(ngayXuat);
        
    }

    
    public static void main(String[] args) {
           
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuXuatForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemPhieuXuatForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nhanVienForm;
    private javax.swing.JLabel movingWindow;
    private javax.swing.JTextField maNV_Label;
    private javax.swing.JLabel ngayXuat_Label;
    private javax.swing.JLabel taoRow_Label;
    private javax.swing.JLabel save_Label;
    private javax.swing.JTable tblCTPN;
    private javax.swing.JLabel [] headerFields;
    private DefaultTableModel model;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
