
package librarymanagementsystem.GUI.ThemSuaGUI;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import librarymanagementsystem.GUI.*;
import librarymanagementsystem.Toolkit.DataProcessing;
import librarymanagementsystem.BUS.QLPhieuMuonBUS;
import librarymanagementsystem.DTO.QLPhieuMuonDTO;

public class ThemPhieuMuonForm extends javax.swing.JFrame{
    int x_Mouse, y_Mouse; // For Moving Window
    static String error_mess;
    DataProcessing dp = new DataProcessing();
    static QLPhieuMuonBUS pmBUS = new QLPhieuMuonBUS();
    
    
    
    public ThemPhieuMuonForm() {
        initComponents();
        setSize(830, 592);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        long millis=System.currentTimeMillis();  
        Date date=new java.sql.Date(millis); 

        jPanel1 = new javax.swing.JPanel();
        addButton = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        movingWindow = new javax.swing.JLabel();
        maThe_Label = new javax.swing.JTextField();
        ngayMuon_Label = new javax.swing.JLabel();
        thoiGianMuon_Field = new javax.swing.JTextField();
        nhanVienForm = new javax.swing.JLabel();
        taoRow_Label = new JLabel();
        tblCTPN = new JTable();
        save_Label=new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        model=new DefaultTableModel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools - 2020-05-28T235936.194.png"))); // NOI18N
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.setBounds(10, 7, 35, 35);
        jPanel1.add(addButton);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools (43).png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        exitButton.setBounds(790, 16, 20, 20);
        jPanel1.add(exitButton);

        movingWindow.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                movingWindowMouseDragged(evt);
            }
        });
        movingWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                movingWindowMousePressed(evt);
            }
        });
        movingWindow.setBounds(0, 0, 830, 60);
        jPanel1.add(movingWindow);
        
        
        maThe_Label.setBackground(new java.awt.Color(245, 247, 250));
        maThe_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        maThe_Label.setText("");
        maThe_Label.setBorder(null);
        maThe_Label.setOpaque(false);
        maThe_Label.setBounds(48, 100, 190, 30);
        jPanel1.add(maThe_Label);

        ngayMuon_Label.setBackground(new java.awt.Color(245, 247, 250));
        ngayMuon_Label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ngayMuon_Label.setText(date.toString());
        ngayMuon_Label.setBorder(null);
        ngayMuon_Label.setOpaque(false);
        ngayMuon_Label.setBounds(310, 100, 210, 30);
        jPanel1.add(ngayMuon_Label);
        
        thoiGianMuon_Field.setBackground(new java.awt.Color(245, 247, 250));
        thoiGianMuon_Field.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thoiGianMuon_Field.setText("");
        thoiGianMuon_Field.setBorder(null);
        thoiGianMuon_Field.setOpaque(false);
        thoiGianMuon_Field.setBounds(557, 100, 160, 30);
        jPanel1.add(thoiGianMuon_Field);
        
        save_Label=new JLabel("Save Table");
        save_Label.setBackground(new java.awt.Color(82, 210, 202));
        save_Label.setFont(new java.awt.Font("Tahoma", 0, 14));
        save_Label.setOpaque(true);
        save_Label.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        save_Label.setBounds(170, 150, 70, 40);
        jPanel1.add(save_Label);
        save_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                for(int i=0;i<tblCTPN.getRowCount();i++){
                    String maPhieuMuon = (String) tblCTPN.getModel().getValueAt(i, 0);
                    String IDSach = (String) tblCTPN.getModel().getValueAt(i, 1);
                    if(check_inputTable(maPhieuMuon, IDSach)==true){
                        System.out.println("Lưu Thành Công");
                        new AlertGUI(3, "Success", "Lưu Thành Công!!!", "Quay Lại").setVisible(true);
                    }else{
                        System.err.println(error_mess);
                        System.out.println("Lưu Thất Bại");
                        new AlertGUI(2, "Error", error_mess, "Quay Lại").setVisible(true);
                    }
                }
            }
        });
        
        taoRow_Label=new JLabel("New Row");
        taoRow_Label.setBackground(new java.awt.Color(82, 210, 202));
        taoRow_Label.setFont(new java.awt.Font("Tahoma", 0, 14));
        taoRow_Label.setOpaque(true);
        taoRow_Label.setHorizontalAlignment((int) CENTER_ALIGNMENT);
        taoRow_Label.setBounds(81, 150, 70, 40);
        jPanel1.add(taoRow_Label);
        taoRow_Label.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Vector header=new Vector();
                header.add("");
                header.add("");
                jScrollPane1.getColumnHeader().setVisible(false);
                if(model.getRowCount()==0){
                    model=new DefaultTableModel(header, 0);
                }
                Vector row=new Vector();
                row.add(dp.next_maMuonSach(pmBUS.getPKey()));
                row.add("IDS");
                model.addRow(row);
                tblCTPN.setModel(model);
            }
        });
        String [] columnName={"MÃ PHIẾU MƯỢN", "ID SÁCH"};
        int x=80,y=208;
        headerFields=new JLabel[columnName.length];
        for(int i=0;i<columnName.length;i++){
            headerFields[i] = new JLabel(columnName[i]);
            headerFields[i].setBorder(BorderFactory.createLineBorder(Color.white));
            headerFields[i].setBounds(x, y, 334, 45);
            headerFields[i].setBackground(new java.awt.Color(82, 210, 202));
            headerFields[i].setFont(new java.awt.Font("Tahoma", 0, 14));
            headerFields[i].setOpaque(true);
            headerFields[i].setHorizontalAlignment((int) CENTER_ALIGNMENT);
            x=x+334;
            jPanel1.add(headerFields[i]);
        }
        jScrollPane1.setViewportView(tblCTPN);
        jScrollPane1.setBounds(80, 250, 670, 300);
        tblCTPN.setRowHeight(40);
        
        jPanel1.add(jScrollPane1);

        nhanVienForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtoolsthempm.png"))); // NOI18N
        nhanVienForm.setBounds(0, 0, 830, 592);
        jPanel1.add(nhanVienForm);
        jPanel1.setBounds(0, 0, 830, 592);
        
        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean check_inputTable(String maPM, String IDSach){
        if (maPM.equals("")){
            error_mess = "Mã Phiếu Mượn trống!!!";
            return false;
        }
        if (IDSach.equals("")){
            error_mess = "ID Sách trống!!!";
            return false;
        }
        if (dp.check_maMuonSach(maPM)!=true){
            error_mess = "Mã Phiếu Mượn nhập sai!!!";
            return false;
        }
        if (dp.check_maSach(IDSach)!=true){
            error_mess = "ID Sách nhập sai!!!";
            return false;
        }
        return true;
    }
    
    private boolean check_input(String maThe,String ngayMuon, String thoiGianMuon){
        if (maThe.equals("")){
            error_mess = "Mã Thẻ trống!!!";
            return false;
        }
        if (ngayMuon.equals("")){
            error_mess = "Ngày Mượn trống!!!";
            return false;
        }
        if (thoiGianMuon.equals("")){
            error_mess = "Thời Gian Mượn trống!!!";
            return false;
        }
        if (dp.check_maThe(maThe)!=true){
            error_mess = "Mã Thẻ nhập sai!!!";
            return false;
        }
        if (dp.check_number(thoiGianMuon)!=true){
            error_mess = "Thời Gian Mượn nhập sai!!!";
            return false;
        }
        
        return true;
    }
    
    private void movingWindowMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingWindowMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        setLocation(x - x_Mouse, y - y_Mouse);
    }//GEN-LAST:event_movingWindowMouseDragged

    
    private void movingWindowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_movingWindowMousePressed
        x_Mouse = evt.getX();
        y_Mouse = evt.getY();
    }//GEN-LAST:event_movingWindowMousePressed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        this.dispose();
    }//GEN-LAST:event_exitButtonMouseClicked

    private ArrayList<String> getIDSach(){
        ArrayList<String> arrMS =new ArrayList<>();
        for(int i=0;i<tblCTPN.getRowCount();i++){
            String IDSach = (String) tblCTPN.getModel().getValueAt(i, 1);
            arrMS.add(IDSach);
        }
        return arrMS;
    }
        
    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {
        String maThe = maThe_Label.getText();
        String ngayMuon = ngayMuon_Label.getText();
        String thoiGianMuon = thoiGianMuon_Field.getText();
        String maPhieuMuon = dp.next_maMuonSach(pmBUS.getPKey());
        ArrayList<String> IDSach = getIDSach();
        if (check_input(maThe, ngayMuon, thoiGianMuon)){
            System.out.println("Nhập Thành Công");
            if (pmBUS.add(maPhieuMuon, maThe, IDSach, ngayMuon, Integer.parseInt(thoiGianMuon), "0000-00-00")){
                new AlertGUI(3, "Success", "Nhập Phiếu Nhập Thành Công!!!", "Quay Lại").setVisible(true);
                this.dispose();
            }
        }
        else{
            System.err.println(error_mess);
            System.out.println("Nhập Thất Bại");
            new AlertGUI(2, "Error", error_mess, "Quay Lại").setVisible(true);
            // Alert Form
        }
        
        System.out.println(maThe);
        System.out.println(ngayMuon);
        System.out.println(thoiGianMuon);
        
    }

    
    public static void main(String[] args) {
           
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuMuonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuMuonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuMuonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemPhieuMuonForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemPhieuMuonForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nhanVienForm;
    private javax.swing.JLabel movingWindow;
    private javax.swing.JTextField maThe_Label;
    private javax.swing.JLabel ngayMuon_Label;
    private javax.swing.JTextField thoiGianMuon_Field;
    private javax.swing.JLabel taoRow_Label;
    private javax.swing.JLabel save_Label;
    private javax.swing.JTable tblCTPN;
    private javax.swing.JLabel [] headerFields;
    private DefaultTableModel model;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
