/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementsystem.GUI.ThemSuaGUI;

import librarymanagementsystem.BUS.*;
import java.awt.Color;

/**
 *
 * @author NTH
 */
public class XemLoaiSachForm extends javax.swing.JFrame {
    
    int x_Mouse, y_Mouse; // For Moving Window
    QLLoaiSachBUS loaiSach = new QLLoaiSachBUS(0);
    
    public XemLoaiSachForm(String maSach) {
        initComponents(maSach);
        setSize(800, 577);
        setLocationRelativeTo(null);
        setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String maSach) {

        jPanel1 = new javax.swing.JPanel();
        tenSach_label = new javax.swing.JLabel();
        hinhSach_label = new javax.swing.JLabel();
        exit_btn = new javax.swing.JLabel();
        moving_window = new javax.swing.JLabel();
        tenTacGia_label = new javax.swing.JLabel();
        tenNXB_label = new javax.swing.JLabel();
        theLoai_label = new javax.swing.JLabel();
        ngonNgu_label = new javax.swing.JLabel();
        namXB_label = new javax.swing.JLabel();
        giaTien_label = new javax.swing.JLabel();
        soTrang_label = new javax.swing.JLabel();
        tomTatNoiDung_label = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        xemForm = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        tenSach_label.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        tenSach_label.setForeground(new java.awt.Color(68, 64, 106));
        tenSach_label.setText(loaiSach.getLoaiSach(maSach).getTenSach());
        tenSach_label.setToolTipText(loaiSach.getLoaiSach(maSach).getTenSach());
        tenSach_label.setBounds(420, 45, 360, 30);
        jPanel1.add(tenSach_label);

        hinhSach_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("../" + loaiSach.getLoaiSach(maSach).getHinh()))); // NOI18N
        hinhSach_label.setBounds(20, 25, 380, 380);
        jPanel1.add(hinhSach_label);

        exit_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools - 2020-06-18T095736.795.png"))); // NOI18N
        exit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_btnMouseClicked(evt);
            }
        });
        exit_btn.setBounds(760, 20, 20, 20);
        jPanel1.add(exit_btn);

        moving_window.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                moving_windowMouseDragged(evt);
            }
        });
        moving_window.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                moving_windowMousePressed(evt);
            }
        });
        moving_window.setBounds(0, 0, 800, 50);
        jPanel1.add(moving_window);

        tenTacGia_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tenTacGia_label.setForeground(new java.awt.Color(51, 51, 51));
        tenTacGia_label.setText(loaiSach.getLoaiSach(maSach).getTenTacGia());
        tenTacGia_label.setToolTipText(loaiSach.getLoaiSach(maSach).getTenTacGia());
        tenTacGia_label.setBounds(540, 90, 250, 30);
        jPanel1.add(tenTacGia_label);

        tenNXB_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        tenNXB_label.setForeground(new java.awt.Color(51, 51, 51));
        tenNXB_label.setText(loaiSach.getLoaiSach(maSach).getTenNXB());
        tenNXB_label.setToolTipText(loaiSach.getLoaiSach(maSach).getTenNXB());
        tenNXB_label.setToolTipText(loaiSach.getLoaiSach(maSach).getTenNXB());
        tenNXB_label.setBounds(600, 130, 190, 30);
        jPanel1.add(tenNXB_label);

        theLoai_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        theLoai_label.setForeground(new java.awt.Color(51, 51, 51));
        theLoai_label.setText(loaiSach.getLoaiSach(maSach).getTheLoai());
        theLoai_label.setToolTipText(loaiSach.getLoaiSach(maSach).getTheLoai());
        theLoai_label.setBounds(520, 170, 260, 30);
        jPanel1.add(theLoai_label);

        ngonNgu_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        ngonNgu_label.setForeground(new java.awt.Color(51, 51, 51));
        ngonNgu_label.setText(loaiSach.getLoaiSach(maSach).getNgonNgu());
        ngonNgu_label.setToolTipText(loaiSach.getLoaiSach(maSach).getNgonNgu());
        ngonNgu_label.setBounds(530, 210, 250, 30);
        jPanel1.add(ngonNgu_label);

        namXB_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        namXB_label.setForeground(new java.awt.Color(51, 51, 51));
        namXB_label.setText(Integer.toString(loaiSach.getLoaiSach(maSach).getNamXB()));
        namXB_label.setToolTipText(Integer.toString(loaiSach.getLoaiSach(maSach).getNamXB()));
        namXB_label.setBounds(250, 410, 140, 30);
        jPanel1.add(namXB_label);

        giaTien_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        giaTien_label.setForeground(new java.awt.Color(51, 51, 51));
        giaTien_label.setText(Integer.toString(loaiSach.getLoaiSach(maSach).getGiaTien()));
        giaTien_label.setToolTipText(Integer.toString(loaiSach.getLoaiSach(maSach).getGiaTien()));
        giaTien_label.setBounds(190, 450, 200, 30);
        jPanel1.add(giaTien_label);

        soTrang_label.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        soTrang_label.setForeground(new java.awt.Color(51, 51, 51));
        soTrang_label.setText(Integer.toString(loaiSach.getLoaiSach(maSach).getSoTrang()));
        soTrang_label.setToolTipText(Integer.toString(loaiSach.getLoaiSach(maSach).getSoTrang()));
        soTrang_label.setBounds(190, 490, 200, 30);
        jPanel1.add(soTrang_label);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setText(loaiSach.getLoaiSach(maSach).getTomTatNoiDung());
        tomTatNoiDung_label.setViewportView(jTextArea1);
        tomTatNoiDung_label.setBounds(420, 290, 342, 230);

        jPanel1.add(tomTatNoiDung_label);

        xemForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("../../images/output-onlinepngtools - 2020-06-18T094450.243.png"))); // NOI18N
        xemForm.setBounds(0, 0, 800, 577);
        jPanel1.add(xemForm);
        jPanel1.setBounds(0, 0, 800, 577);

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>                        

    private void exit_btnMouseClicked(java.awt.event.MouseEvent evt) {                                      
        this.dispose();
    }                                     

    private void moving_windowMouseDragged(java.awt.event.MouseEvent evt) {                                           
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - x_Mouse, y - y_Mouse);
    }                                          

    private void moving_windowMousePressed(java.awt.event.MouseEvent evt) {                                           
        x_Mouse = evt.getX();
        y_Mouse = evt.getY();
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XemLoaiSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XemLoaiSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XemLoaiSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XemLoaiSachForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new XemLoaiSachForm("S000005").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel exit_btn;
    private javax.swing.JLabel giaTien_label;
    private javax.swing.JLabel hinhSach_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel moving_window;
    private javax.swing.JLabel namXB_label;
    private javax.swing.JLabel ngonNgu_label;
    private javax.swing.JLabel soTrang_label;
    private javax.swing.JLabel tenNXB_label;
    private javax.swing.JLabel tenSach_label;
    private javax.swing.JLabel tenTacGia_label;
    private javax.swing.JLabel theLoai_label;
    private javax.swing.JScrollPane tomTatNoiDung_label;
    private javax.swing.JLabel xemForm;
    // End of variables declaration                   
}